In [1]:
#import libraries
import numpy as np
import pandas as pd


#import datasets
vars_ = pd.read_csv('vars-sample (2).csv',sep=';' , engine='python')
target = pd.read_csv('target-sample.csv', sep=';' , engine='python')
vars_.head()

id  Factor_1  Factor_2 Factor_3  Factor_4  Factor_5  Factor_6  Factor_7  \
0   1         0         0        0  0,176471    439078        -1         0   
1   2         0         0        0         0    803000         0         0   
2   3         0         0   0,2862         0     25000         0         0   
3   4         1         5        0  0,709677    851360         0         0   
4   5         1         0        0         0      4000         0         0   

   Factor_8  Factor_9  Factor_10  Factor_11  Factor_12  
0         0       1,4          4          0          0  
1         1  1,818182          9          0          0  
2         0  1,555556          5          0          0  
3         1         1          0          1          0  
4         1  1,071429          1          0          0

In [3]:
target.head()

id  status
0   1       0
1   2       0
2   3       0
3   4       1
4   5       1

## Clean Dataset

In [4]:
vars_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5358 entries, 0 to 5357
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         5358 non-null   int64 
 1   Factor_1   5358 non-null   int64 
 2   Factor_2   5358 non-null   int64 
 3   Factor_3   5358 non-null   object
 4   Factor_4   5358 non-null   object
 5   Factor_5   5358 non-null   int64 
 6   Factor_6   5358 non-null   int64 
 7   Factor_7   5358 non-null   int64 
 8   Factor_8   5358 non-null   int64 
 9   Factor_9   5358 non-null   object
 10  Factor_10  5358 non-null   int64 
 11  Factor_11  5358 non-null   int64 
 12  Factor_12  5358 non-null   int64 
dtypes: int64(10), object(3)
memory usage: 544.3+ KB


In [5]:
#Check null values
vars_.isnull().sum()

id           0
Factor_1     0
Factor_2     0
Factor_3     0
Factor_4     0
Factor_5     0
Factor_6     0
Factor_7     0
Factor_8     0
Factor_9     0
Factor_10    0
Factor_11    0
Factor_12    0
dtype: int64

In [2]:
#Check null values
target.isnull().sum()

id        0
status    0
dtype: int64

In [57]:
#join dataset
final = vars_.merge(target,left_on='id', right_on='id', suffixes=(False, False))
final

id  Factor_1  Factor_2  Factor_3  Factor_4  Factor_5  Factor_6  \
0        1         0         0         0  0,176471    439078        -1   
1        2         0         0         0         0    803000         0   
2        3         0         0    0,2862         0     25000         0   
3        4         1         5         0  0,709677    851360         0   
4        5         1         0         0         0      4000         0   
...    ...       ...       ...       ...       ...       ...       ...   
5353  5354         1        11  0,329408  0,230769    184000         1   
5354  5355         1         1  0,033683  0,181818    516253         0   
5355  5356         0         0         0  0,166667   1268556        -1   
5356  5357         1         2         0       0,2    127938         0   
5357  5358         0         0         0         0    204508         0   

      Factor_7  Factor_8  Factor_9  Factor_10  Factor_11  Factor_12  status  
0            0         0       1,4          4          0          0       0  
1            0         1  1,818182          9          0          0       0  
2            0         0  1,555556          5          0          0       0  
3            0         1         1          0          1          0       1  
4            0         1  1,071429          1          0          0       1  
...        ...       ...       ...        ...        ...        ...     ...  
5353         0         1       1,8          4          0          0       0  
5354         0         0  1,333333          5          0          0       0  
5355         0         1         1          0          0          0       0  
5356         0         1  2,222222         11          0          0       1  
5357         0         1         1          0          0          1       0  

[5358 rows x 14 columns]

In [176]:
def ChangeFloat(column):
    list = []
    for index in column:
        index = index.replace(',','.')
        list.append(index)
    data = np.array(list)
    return data

In [183]:
final['Factor_3'] = ChangeFloat(final['Factor_3']).tolist()
final['Factor_3'] = final['Factor_3'].astype(float)

final['Factor_4'] = ChangeFloat(final['Factor_4']).tolist()
final['Factor_4'] = final['Factor_4'].astype(float)

final['Factor_9'] = ChangeFloat(final['Factor_9']).tolist()
final['Factor_9'] = final['Factor_9'].astype(float)

final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5358 entries, 0 to 5357
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   id         5358 non-null   int64  
 1   Factor_1   5358 non-null   int64  
 2   Factor_2   5358 non-null   int64  
 3   Factor_3   5358 non-null   float64
 4   Factor_4   5358 non-null   float64
 5   Factor_5   5358 non-null   int64  
 6   Factor_6   5358 non-null   int64  
 7   Factor_7   5358 non-null   int64  
 8   Factor_8   5358 non-null   int64  
 9   Factor_9   5358 non-null   float64
 10  Factor_10  5358 non-null   int64  
 11  Factor_11  5358 non-null   int64  
 12  Factor_12  5358 non-null   int64  
 13  status     5358 non-null   int64  
dtypes: float64(3), int64(11)
memory usage: 627.9 KB


In [58]:

final = final.replace('[^\d.]','',regex = True) 

In [5]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5358 entries, 0 to 5357
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         5358 non-null   int64 
 1   Factor_1   5358 non-null   int64 
 2   Factor_2   5358 non-null   int64 
 3   Factor_3   5358 non-null   object
 4   Factor_4   5358 non-null   object
 5   Factor_5   5358 non-null   int64 
 6   Factor_6   5358 non-null   int64 
 7   Factor_7   5358 non-null   int64 
 8   Factor_8   5358 non-null   int64 
 9   Factor_9   5358 non-null   object
 10  Factor_10  5358 non-null   int64 
 11  Factor_11  5358 non-null   int64 
 12  Factor_12  5358 non-null   int64 
 13  status     5358 non-null   int64 
dtypes: int64(11), object(3)
memory usage: 627.9+ KB


In [161]:
final['Factor_3'] = pd.to_numeric(final['Factor_3'],errors = 'coerce')
final['Factor_4'] = pd.to_numeric(final['Factor_4'],errors = 'coerce')
final['Factor_9'] = pd.to_numeric(final['Factor_9'],errors = 'coerce')

In [59]:
final["Factor_3"] = final.Factor_3.astype(float)
final["Factor_4"] = final.Factor_4.astype(float)
final["Factor_9"] = final.Factor_9.astype(float)

In [7]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5358 entries, 0 to 5357
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   id         5358 non-null   int64  
 1   Factor_1   5358 non-null   int64  
 2   Factor_2   5358 non-null   int64  
 3   Factor_3   5358 non-null   float64
 4   Factor_4   5358 non-null   float64
 5   Factor_5   5358 non-null   int64  
 6   Factor_6   5358 non-null   int64  
 7   Factor_7   5358 non-null   int64  
 8   Factor_8   5358 non-null   int64  
 9   Factor_9   5358 non-null   float64
 10  Factor_10  5358 non-null   int64  
 11  Factor_11  5358 non-null   int64  
 12  Factor_12  5358 non-null   int64  
 13  status     5358 non-null   int64  
dtypes: float64(3), int64(11)
memory usage: 627.9 KB


In [163]:
final.isnull()

id  Factor_1  Factor_2  Factor_3  Factor_4  Factor_5  Factor_6  \
0     False     False     False     False     False     False     False   
1     False     False     False     False     False     False     False   
2     False     False     False     False     False     False     False   
3     False     False     False     False     False     False     False   
4     False     False     False     False     False     False     False   
...     ...       ...       ...       ...       ...       ...       ...   
5353  False     False     False     False     False     False     False   
5354  False     False     False     False     False     False     False   
5355  False     False     False     False     False     False     False   
5356  False     False     False     False     False     False     False   
5357  False     False     False     False     False     False     False   

      Factor_7  Factor_8  Factor_9  Factor_10  Factor_11  Factor_12  status  
0        False     False     False      False      False      False   False  
1        False     False     False      False      False      False   False  
2        False     False     False      False      False      False   False  
3        False     False     False      False      False      False   False  
4        False     False     False      False      False      False   False  
...        ...       ...       ...        ...        ...        ...     ...  
5353     False     False     False      False      False      False   False  
5354     False     False     False      False      False      False   False  
5355     False     False     False      False      False      False   False  
5356     False     False     False      False      False      False   False  
5357     False     False     False      False      False      False   False  

[5358 rows x 14 columns]

In [41]:
final = final.drop(['Factor_3','Factor_4','Factor_9'],axis =1)

In [61]:
#create the X and Y
X = final.iloc[:,0:12]

y = final[['status']]
y = y.to_numpy()

In [62]:
X.shape,y.shape

((5358, 12), (5358, 1))

## Create Logistic Regression model

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import linear_model

In [92]:
#Create model
clf = linear_model.LogisticRegression()
clf

LogisticRegression()

In [69]:
#Create array
X = X.to_numpy()

In [70]:
X[4]

array([5.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 4.000000e+03, 0.000000e+00, 0.000000e+00,
       1.000000e+00, 1.071429e+06, 1.000000e+00, 0.000000e+00])

In [27]:
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [87]:
#Set value by model
clf.fit(X, y.ravel())

LogisticRegression(max_iter=4000, random_state=1000)

In [35]:
X[4]

array([5.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 4.e+03, 0.e+00, 0.e+00,
       1.e+00])

In [88]:
ar = clf.predict(X)
df = pd.DataFrame(ar,columns = ['Status'])
df.head(15)

Status
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0

## Train and test split model (80/20)

In [73]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2,random_state=1000)

In [49]:
#Set train value by model
clf.fit(X_train, Y_train.ravel())

LogisticRegression()

In [50]:
d = clf.predict_proba(X_test)
d


array([[0.52664739, 0.47335261],
       [0.75388794, 0.24611206],
       [0.98688532, 0.01311468],
       ...,
       [0.75840472, 0.24159528],
       [0.54356933, 0.45643067],
       [0.79525048, 0.20474952]])

In [51]:
#Predicted status value
d = pd.DataFrame(clf.predict(X_test),columns = ['status'])
d.head(51)

status
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
30       0
31       0
32       0
33       0
34       0
35       0
36       0
37       0
38       0
39       0
40       0
41       0
42       0
43       0
44       0
45       0
46       0
47       0
48       0
49       0
50       0

In [52]:
#Actual status value
print(Y_test)

[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]


In [53]:
#Model performence 
print('Accuracy of LogRegression model: ', clf.score(X_test,Y_test))

Accuracy of LogRegression model:  0.773320895522388


## Create model by use Random Forest Classifier

In [74]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
model = RandomForestClassifier()
model.fit(X, y.ravel())

RandomForestClassifier()

In [75]:
print(model.feature_importances_)

[0.23420506 0.04208759 0.05108801 0.08676665 0.09299498 0.2011467
 0.02266348 0.02284819 0.02229295 0.11802372 0.10286588 0.0030168 ]


In [76]:
X[4]

array([5.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 4.000000e+03, 0.000000e+00, 0.000000e+00,
       1.000000e+00, 1.071429e+06, 1.000000e+00, 0.000000e+00])

In [77]:
print(model.predict([[1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       4.000000e+03, 0.000000e+00, 0.000000e+00, 1.000000e+00,
       1.071429e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00]]))

[0]


In [78]:
model.predict(X)

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

## Train and Test split

In [79]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.4)

In [80]:
model.fit(X_train, Y_train.ravel())

RandomForestClassifier()

In [81]:
df  = pd.DataFrame(model.predict(X_test),columns = ['Status'])
df.head(51)

Status
0        0
1        1
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
30       1
31       0
32       0
33       0
34       0
35       0
36       0
37       0
38       0
39       0
40       0
41       0
42       0
43       0
44       0
45       0
46       0
47       0
48       0
49       0
50       0

In [82]:
print('Accuracy of RF classifier:', model.score(X_test, Y_test))

Accuracy of RF classifier: 0.7779850746268657


In [83]:
#Result by Random Forest Classifier
RanForClass  = pd.DataFrame(model.predict(X),columns = ['Status'])
RanForClass

Status
0          0
1          0
2          0
3          0
4          1
...      ...
5353       1
5354       0
5355       0
5356       1
5357       0

[5358 rows x 1 columns]

In [98]:
#Result by LogRegression
LogRegres  = pd.DataFrame(clf.predict(X),columns = ['Status'])
LogRegres

Status
0          0
1          0
2          0
3          0
4          0
...      ...
5353       0
5354       0
5355       0
5356       0
5357       0

[5358 rows x 1 columns]

In [84]:
final['Вероятность наступление события status'] = model.predict(X)

In [85]:
final

id  Factor_1  Factor_2  Factor_3  Factor_4  Factor_5  Factor_6  \
0        1         0         0       0.0  176471.0    439078        -1   
1        2         0         0       0.0       0.0    803000         0   
2        3         0         0    2862.0       0.0     25000         0   
3        4         1         5       0.0  709677.0    851360         0   
4        5         1         0       0.0       0.0      4000         0   
...    ...       ...       ...       ...       ...       ...       ...   
5353  5354         1        11  329408.0  230769.0    184000         1   
5354  5355         1         1   33683.0  181818.0    516253         0   
5355  5356         0         0       0.0  166667.0   1268556        -1   
5356  5357         1         2       0.0       2.0    127938         0   
5357  5358         0         0       0.0       0.0    204508         0   

      Factor_7  Factor_8   Factor_9  Factor_10  Factor_11  Factor_12  status  \
0            0         0       14.0          4          0          0       0   
1            0         1  1818182.0          9          0          0       0   
2            0         0  1555556.0          5          0          0       0   
3            0         1        1.0          0          1          0       1   
4            0         1  1071429.0          1          0          0       1   
...        ...       ...        ...        ...        ...        ...     ...   
5353         0         1       18.0          4          0          0       0   
5354         0         0  1333333.0          5          0          0       0   
5355         0         1        1.0          0          0          0       0   
5356         0         1  2222222.0         11          0          0       1   
5357         0         1        1.0          0          0          1       0   

      Вероятность наступление события status  
0                                          0  
1                                          0  
2                                          0  
3                                          0  
4                                          1  
...                                      ...  
5353                                       1  
5354                                       0  
5355                                       0  
5356                                       1  
5357                                       0  

[5358 rows x 15 columns]

In [122]:
final.to_excel('result.xlsx', index = False)